apiVersion: v1
kind: Service
metadata:
  name: "green-capstone-service"
  namespace: "green-capstone"
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app: "capstone-project-app"