apiVersion: v1
kind: Service
metadata:
  name: capstone-service-green
  labels:
    app: capstone-project-cloud-devops
    role: green
spec:
  type: LoadBalancer
  selector:
    app: capstone-project-cloud-devops
    role: green
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
      targetPort: 5000